apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
  - port: 80
  selector:
    app: backend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "configwriter",
                "image": "busybox",
                "command": [
                    "sh",
                    "-c",
                    "`echo \"
                      events{}
                      http{
                        server {
                            location /sleep {
                              content_by_lua ''
                                local start = ngx.now();
                                ngx.sleep(0.5);
                                ngx.say(ngx.now() - start);
                              '';
                            }
                        }
                      }\" > /usr/local/nginx/conf/nginx.conf`"
                ],
                "volumeMounts": [
                    {
                        "name": "config",
                        "mountPath": "/usr/local/nginx/conf"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
        command:
        - nginx
        args:
        - -g
        - "daemon off;"
        - -c
        - "/usr/local/nginx/conf/nginx.conf"
        volumeMounts:
        - name: config
          mountPath: /usr/local/nginx/conf
      volumes:
      - name: config
        emptyDir: {}

